export const SBL = '['
export const SBR = ']'
export const CBL = '{'
export const CBR = '}'
export const Dot = '.'
export const Colon = ':'
export const Comma = ','
export const Bracket = [SBL, SBR, CBL, CBR]
export const Operator = [Dot, Colon, Comma]
export const All = Bracket.concat(Operator)
