declare const SpeedMeasurePlugin: any;
declare const TerserPlugin: any;
declare const MiniCssExtractPlugin: any;
declare const CssMinimizerPlugin: any;
declare const glob: any;
declare const PurgeCSSPlugin: any;
declare const merge: any;
declare const ESBuildMinifyPlugin: any;
declare const BundleAnalyzerPlugin: any;
declare const outputPath: any, appPath: any;
declare const common: any;
