export const $type = Symbol.for('motion:type')
export const $id = Symbol.for('motion:id')
export const $status = Symbol.for('motion:status')
export const $animated = Symbol.for('motion:animated')
export const $observer = Symbol.for('motion:observer')
export const $motion = Symbol.for('motion:value')
