export const $id = Symbol.for('motion:id')
export const $cache = Symbol.for('motion:cache')
export const $animations = Symbol.for('motion:animations')
export const $control = Symbol.for('motion:playback')
export const $promise = Symbol.for('motion:promise')
