export declare const CWD: string;
export declare const KPI_CONFIG: string;
export declare const SRC_DIR: string;
export declare const LIB_DIR: string;
export declare const ES_DIR: string;
export declare const UMD_DIR: string;
export declare const TYPES_DIR: string;
export declare const DOCS_DIR: string;
export declare const UI_PACKAGE_JSON: string;
export declare const ESLINT_EXTENSION: string[];
export declare const RESOLVE_EXTENSION: string[];
export declare const SCRIPTS_EXTENSION: string[];
export declare const PUBLIC_ENTRY: string[];
export declare const STYLE_DIR_NAME = "style";
export declare const EXAMPLE_DIR_NAME = "example";
export declare const EXAMPLE_LOCALE_DIR_NAME = "locale";
export declare const EXAMPLE_DIR_ENTRY = "index.tsx";
export declare const DOCS_DIR_NAME = "docs";
export declare const TESTS_DIR_NAME = "__tests__";
export declare const GENERATE_DIR: string;
export declare const CLI_PACKAGE_JSON: string;
export declare const SITE_CONFIG: string;
